# Generated by Django 5.0.2 on 2024-02-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_song_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.CharField(default='Max Mustermann', max_length=100),
        ),
    ]
