# Generated by Django 5.0.2 on 2024-02-25 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_vote_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='pub_date',
            field=models.CharField(default=datetime.date(2024, 2, 25), max_length=20),
        ),
    ]
