# Generated by Django 5.0.2 on 2024-02-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_song_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='abstain_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='against_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='for_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='night_votes',
            field=models.IntegerField(default=0),
        ),
    ]
