# Generated by Django 5.0.2 on 2024-02-27 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_song_abstain_votes_song_against_votes_song_for_votes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Max Mustermann', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='pub_date',
            field=models.CharField(default=datetime.date(2024, 2, 27), max_length=20),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
